<?php require('template/header.phtml');?>

<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Incoming Requests</h1>
            <hr>
        </div>

<?php foreach($view->incoming as $userData) { ?>
            <div class="col-3 mb-3">
                <div class="card w-100">
                    <div class="card-body">
                    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-horizontal">

                        <img class="profile-pic mr-3 img-fluid" src="/CSC_MVC/images/<?php echo $userData->getProfilePic();?>" alt="placeholder">
                        <div class="flex-column">
                            <h3 class="mb-0 font-weight-normal"><?php echo $userData->getFirstName() . ' ' . $userData->getLastName(); ?></h3>
                            <button type = "submit" class = "btn btn-primary" name = "buttonview" value ="<?php echo $userData->getID()?>">Go To Profile</button>
                            <button type = "submit" class = "btn btn-success" name = "accept" value ="<?php echo $userData->getID()?>"> Accept </button>
                        </div>
                    </form>
                    </div>
                </div>
    </div>
<?php } ?>
<hr>
<div class="col-12">
    <h1>Pending Requests</h1>
    <hr>
</div>

<?php foreach($view->pending as $userData) { ?>
<div class="col-3 mb-3">
    <div class="card w-100">
        <div class="card-body">
        <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-horizontal">

            <img class="profile-pic mr-3 img-fluid" src="/CSC_MVC/images/<?php echo $userData->getProfilePic();?>" alt="placeholder">
            <div class="flex-column">
                <h3 class="mb-0 font-weight-normal"><?php echo $userData->getFirstName() . ' ' . $userData->getLastName(); ?></h3>
                <button type = "submit" class = "btn btn-primary" name = "buttonview" value ="<?php echo $userData->getID()?>">Go To Profile</button>
            </div>
        </form>
        </div>
    </div>
</div>
<?php } ?>
<hr>
<div class="col-12">
    <h1>Friends</h1>
    <hr>
</div>
<?php foreach($view->friends as $userData) { ?>
            <div class="col-3 mb-3">
                <div class="card w-100">
                    <div class="card-body">
                    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-horizontal">

                        <img class="profile-pic mr-3 img-fluid" src="/CSC_MVC/images/<?php echo $userData->getProfilePic();?>" alt="placeholder">
                        <div class="flex-column">
                            <h3 class="mb-0 font-weight-normal"><?php echo $userData->getFirstName() . ' ' . $userData->getLastName(); ?></h3>
                            <button type = "submit" class = "btn btn-primary" name = "buttonview" value ="<?php echo $userData->getID()?>">Go To Profile</button>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
<?php } ?>

</div>
</div>
