<?php require('template/header.phtml');

$friendsLocations = array();

foreach ($view->friends as $userData) {
$friendsLocations[] = $userData->getLatitude();
$friendsLocations[] = $userData->getLongitude();
}

?>

<input type="hidden" name="current-id" id="current-id" value="<?php echo $_SESSION['userid'] ?>" />
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Incoming Requests</h1>
            <hr>
        </div>

<?php foreach($view->incoming as $userData) { ?>
            <div class="col-3 mb-3">
                <div class="card w-100">
                    <div class="card-body">
                    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-horizontal">

                        <img class="profile-pic mr-3 img-fluid" src="/CSC_MVC/images/<?php echo $userData->getProfilePic();?>" alt="placeholder">
                        <div class="flex-column">
                            <h3 class="mb-0 font-weight-normal"><?php echo $userData->getFirstName() . ' ' . $userData->getLastName(); ?></h3>
                            <button type = "submit" class = "btn btn-primary" name = "buttonview" value ="<?php echo $userData->getID()?>">Go To Profile</button>
                            <button type = "submit" class = "btn btn-success" name = "accept" value ="<?php echo $userData->getID()?>"> Accept </button>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
<?php } ?>
<hr>
<div class="col-12">
    <h1>Pending Requests</h1>
    <hr>
</div>

<?php foreach($view->pending as $userData) { ?>
<div class="col-3 mb-3">
    <div class="card w-100">
        <div class="card-body">
        <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-horizontal">

            <img class="profile-pic mr-3 img-fluid" src="/CSC_MVC/images/<?php echo $userData->getProfilePic();?>" alt="placeholder">
            <div class="flex-column">
                <h3 class="mb-0 font-weight-normal"><?php echo $userData->getFirstName() . ' ' . $userData->getLastName(); ?></h3>
                <button type = "submit" class = "btn btn-primary" name = "buttonview" value ="<?php echo $userData->getID()?>">Go To Profile</button>
            </div>
        </form>
        </div>
    </div>
</div>
<?php } ?>
<hr>
<div class="col-12">
    <h1>Friends</h1>
    <hr>
</div>
</div>
</div>

<div class="container mt-4">
            <div class="row gutters-sm">
                <?php foreach($view->friends as $userData) { ?>
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="/CSC_MVC/images/<?php echo $userData->getProfilePic() ?>" alt="Admin" class="rounded-circle" width="150">
                                <div class="mt-3">
                                    <h4><?php echo $userData->getFirstName() . ' ' . $userData->getLastName() ?></h4>
                                    <p class="text-muted font-size-sm"><?php echo $userData->getUsername() ?></p>
                                    <p class="text-muted font-size-sm">Location: <?php echo $userData->getLongitude()?>, <?php echo $userData->getLatitude()?></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
<?php } ?>
        <?php foreach($view->map as $myData) { ?>
        <script>
            let map, infoWindow,marker;

            function initMap() {

                map = new google.maps.Map(document.getElementById("map"), {
                    center: { lat: -34.397, lng: 150.644 },
                    zoom: 2,
                });
                infoWindow = new google.maps.InfoWindow();

                var friendL = <?php echo json_encode($friendsLocations); ?>;

                for (var i = 0; i < friendL.length; i = i+2) {
                    var friend = { lat: Number(friendL[i]), lng:  Number(friendL[i+1])};
                    marker = new google.maps.Marker({
                        position: friend,
                        map,
                        title: "Hello World!",
                    });
                }
            }
            window.initMap = initMap;
        </script>

    <div class="col-md-8">
        <div class="row">
            <div class="col-sm-12">
                <div id="map"></div>
                <script
                        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCxgjgz-rhF9DznXzbBYHXNNCTOGN1Vgtg&callback=initMap&v=weekly"
                        defer
                ></script>
            </div>
        </div>
    </div>
        <?php } ?>
</div>
</div>

<?php require('template/footer.phtml') ?>
