<?php require('template/header.phtml') ?>
    <div class="container">
        <div class="row">
            <div class="span12">
                <h1> Login </h1>
                <hr>
                <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-horizontal">
                    <div class="control-group">
                        <label class="control-label">Username</label>
                        <div class="controls">
                            <input name = "username" type="text" placeholder="Username">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Password</label>
                        <div class="controls">
                            <input name = "password" type="password" placeholder="Password">
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" name = "submit" class="btn btn-primary">Login</button>
                        <button type="reset" class="btn">Reset</button>
                    </div>
                    <div>
                        <h4 class="muted">Don't have an account yet?</h4>
                        <button onclick="location.href='register.php'">Register</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

<?php require('template/footer.phtml') ?>