<?php require('template/header.phtml') ?>
    <div class="container mt-4">
        <div class="row">
            <div class="col"></div>
            <div class="col">
                <h1> Login </h1>
                <hr>
                <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label">Username</label>
                        <input name = "username" type="text" placeholder="Username" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Password</label>    
                        <input name = "password" type="password" placeholder="Password" class="form-control">
                    </div>
                    <div class="form-actions mt-2">
                        <button type="submit" name = "submit" class="btn btn-primary">Login</button>
                        <button type="reset" class="btn">Reset</button>
                    </div>
                </form>
                <p class="text-muted mt-1">Don't have an account yet?</p>
                <a href="register.php" class="btn btn-primary">Register</a>
            </div>

            <div class="col"></div>
        </div>
    </div>

<?php require('template/footer.phtml') ?>