<?php require('template/header.phtml')?>

<?php foreach($view->userData as $userData) { ?>
<div class="container mt-4">
        <div class="row gutters-sm">
        <div class="col-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex flex-column align-items-center text-center">
                        <img src="/CSC_MVC/images/<?php echo $userData->getProfilePic() ?>" alt="Admin" class="rounded-circle" width="150">
                        <div class="mt-3">
                            <h4><?php echo $userData->getFirstName() . ' ' . $userData->getLastName() ?></h4>
                            <p class="text-muted font-size-sm"><?php echo $userData->getUsername() ?></p>
                            <a class="btn btn-outline-primary" href="changepic.php">Edit Profile Pic</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-8">
        <div class="card mb-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <?php echo $userData->getEmail() ?>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Username</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <?php echo $userData->getUsername() ?>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Location</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <p><?php echo $userData->getLongitude()?> , <?php echo $userData->getLatitude()?></p>
                    </div>
                </div>

                <script>
                    let map, infoWindow;

                    function initMap() {
                        map = new google.maps.Map(document.getElementById("map"), {
                            center: { lat: <?php echo $userData->getLatitude()?>, lng:  <?php echo $userData->getLongitude()?>},
                            zoom: 6,
                        });
                        infoWindow = new google.maps.InfoWindow();

                        const locationButton = document.createElement("button");

                        locationButton.textContent = "Update Location";
                        locationButton.classList.add("custom-map-control-button");
                        map.controls[google.maps.ControlPosition.TOP_CENTER].push(locationButton);
                        locationButton.addEventListener("click", () => {
                            // Try HTML5 geolocation.
                            if (navigator.geolocation) {
                                navigator.geolocation.getCurrentPosition(
                                    (position) => {
                                        const pos = {
                                            lat: position.coords.latitude,
                                            lng: position.coords.longitude,
                                        };

                                        infoWindow.setPosition(pos);
                                        infoWindow.setContent("Location found.");
                                        infoWindow.open(map);
                                        map.setCenter(pos);
                                    },
                                    () => {
                                        handleLocationError(true, infoWindow, map.getCenter());
                                    }
                                );
                            } else {
                                // Browser doesn't support Geolocation
                                handleLocationError(false, infoWindow, map.getCenter());
                            }
                        });
                    }

                    function handleLocationError(browserHasGeolocation, infoWindow, pos) {
                        infoWindow.setPosition(pos);
                        infoWindow.setContent(
                            browserHasGeolocation
                                ? "Error: The Geolocation service failed."
                                : "Error: Your browser doesn't support geolocation."
                        );
                        infoWindow.open(map);
                    }

                    window.initMap = initMap;
                </script>

                <div class="row">
                    <div class="col-sm-12">
                        <div id="map"></div>
                        <script
                                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCxgjgz-rhF9DznXzbBYHXNNCTOGN1Vgtg&callback=initMap&v=weekly"
                                defer
                        ></script>
                    </div>
                </div>
<?php } ?>

<?php require('template/footer.phtml') ?>