<?php require('template/header.phtml')?>

<?php foreach($view->userData as $userData) { ?>
<div class="container">
    <div class="main-body">
        <div class="row gutters-sm">
        <div class="col-md-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex flex-column align-items-center text-center">
                        <img src="/CSC_MVC/images/<?php echo $userData->getProfilePic() ?>" alt="Admin" class="rounded-circle" width="150">
                        <div class="mt-3">
                            <h4><?php echo $userData->getFirstName() . ' ' . $userData->getLastName() ?></h4>
                            <p class="text-muted font-size-sm"><?php echo $userData->getUsername() ?></p>
                            <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-horizontal">
                                <button class="btn btn-outline-primary" name="Edit Profile">Edit Profile Pic</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
        <div class="card mb-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <?php echo $userData->getEmail() ?>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Username</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <?php echo $userData->getUsername() ?>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Location</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <?php echo $userData->getLocation() ?>
                    </div>
                </div>
        </div>
    </div>
<?php } ?>

<?php require('template/footer.phtml') ?>