<?php require('template/header.phtml')?>

<?php foreach($view->userData as $userData) { ?>
<input type="hidden" name="current-id" id="current-id" value="<?php echo $userData->getID() ?>" />
<div class="container mt-4">
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="/CSC_MVC/images/<?php echo $userData->getProfilePic() ?>" alt="Admin" class="rounded-circle" width="150">
                            <div class="mt-3">
                                <h4><?php echo $userData->getFirstName() . ' ' . $userData->getLastName() ?></h4>
                                <p class="text-muted font-size-sm"><?php echo $userData->getUsername() ?></p>
                                <?php if(!$addFriend->checkFriend($_SESSION['userid'], $id)) { ?>
                                <form method="post">
                                    <input type="hidden" name="addFriendId" value="<?php echo $userData->getID()?>"/>
                                    <input class="btn btn-success" value="Add Friend" type="submit" />
                                </form>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                <?php echo $userData->getEmail() ?>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Username</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                <?php echo $userData->getUsername() ?>
                            </div>
                        </div>
                        <hr>

                        <?php if($addFriend->checkFriend($_SESSION['userid'], $id)) { ?>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Location</h6>
                            </div>
                            <div class="col-sm-9 text-secondary" id="current-user-location">
                                <p><?php echo $userData->getLatitude()?> , <?php echo $userData->getLongitude()?></p>
                            </div>
                        </div>

                        <script>
                            let map, infoWindow,marker;

                            function initMap() {

                                const location = { lat: <?php echo $userData->getLatitude()?>, lng: <?php echo $userData->getLongitude()?> };

                                map = new google.maps.Map(document.getElementById("map"), {
                                    center: location,
                                    zoom: 8,
                                });
                                infoWindow = new google.maps.InfoWindow();

                                marker = new google.maps.Marker({
                                    position: location,
                                    map,
                                    title: "Hello World!",
                                });
                            }

                            window.initMap = initMap;
                        </script>

                        <div class="row">
                            <div class="col-sm-12">
                                <div id="map"></div>
                                <script
                                        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCxgjgz-rhF9DznXzbBYHXNNCTOGN1Vgtg&callback=initMap&v=weekly"
                                        defer
                                ></script>
                                <script
                                        src="/js/updatelocation.js"
                                        defer
                                ></script>
                        </div>
                        <?php } else { ?>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Location</h6>
                            </div>
                            <div class="col-sm-9 text-secondary" id="current-user-location">
                                <p>Add as friend to see location!</p>
                            </div>
<?php } } ?>

<?php require('template/footer.phtml') ?>
