<?php require('template/header.phtml')?>

    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col">
                <h1> Register </h1>
                <p class="text-muted"> Please fill out the form below to make your account! </p>
                <hr>
                <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="form-horizontal" enctype="multipart/form-data">
                    <div class="form-group">
                        <label class="control-label">First Name</label>
                        <input name="firstname" type="text" placeholder="First Name" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Last Name</label>
                        <input name="lastname" type="text" placeholder="Last Name" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Email</label>
                        <input name="email" type="email" placeholder="Email" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Username</label>
                        <input name="username" type="text" placeholder="Username" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Password</label>
                        <input name="password" type="password" placeholder="Password" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Confirm Password</label>
                        <input name="cpassword" type="password" placeholder="Confirm Password" class="form-control">
                    </div>
                    <div>
                        <label class="control-label">Optional: Add a Profile Picture!</label>
                        <div class="custom-file">
                            <input name="fileToUpload" id="fileToUpload" type="file" class="custom-file-input">
                            <label class="custom-file-label" for="fileToUpload">Choose file</label>
                        </div>
                    </div>
                    <div class="form-actions mt-2">
                        <button type="submit" name="submit" class="btn btn-primary">Sign Up</button>
                        <button type="reset" class="btn">Reset</button>
                    </div>
                </form>
            </div>
            <div class="col"></div>
        </div>
    </div>
</body>

<?php require('template/footer.phtml') ?>