<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/CSC_MVC/css/bootstrap.css" rel="stylesheet">
    <link href="/CSC_MVC/css/custom.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a href="index.php?index" class="navbar-brand">SpaceBook</a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a href="index.php?index" class="nav-link">Home</a>
            </li>
            <?php if(isset($_SESSION['userid'])) { ?>
                <li class="nav-item">
                    <a href="index.php?myprofile" class="nav-link">My Profile</a>
                </li>
                <li class="nav-item">
                    <a href="index.php?friends" class="nav-link">My Friends</a>
                </li>
                <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" class="d-flex">
                    <input class="form-control me-2" name="searchContent"type="search" placeholder="Search ..." aria-label="Search">
                </form>
            <?php } ?>
        </ul>
        <ul class="navbar-nav">
            <?php if(isset($_SESSION['userid'])) { ?>
                <li class="nav-item"><a href="index.php?logout" class="nav-link">Logout</a></li>   
                <?php } else { ?>
                    <li class="nav-item"><a href="index.php?login" class="nav-link">Login</a></li>
                    <li class="nav-item"><a href="index.php?register" class="nav-link">Register</a></li>
                <?php } ?>
        </ul>
        </div>
    </div>
</nav>
